version: "3.10"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
    - "8090:8090"
    volumes:
    - ./app:/app
    command: >
      sh -c "python3 manage.py postgreconf &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8090"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=pass1234
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=pass1234

volumes:
  dev-db-data: