# Generated by Django 4.1.3 on 2022-11-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
